baseURL = 'http://www.dipsmokehouse.fr/dev/'
languageCode = 'fr-FR'
title = 'DIP SmokeHouse - BBQ Grill - Sophia Antipolis'
theme = "smokyBeef"
[params]
  title = "DIP SmokeHouse - BBQ Grill - Sophia Antipolis"
  description = "Restaurant de viandes cuites au Smoker, à Sophia Antipolis"